#!/usr/bin/env zsh

source "$HOME/.zshsystemconf"

# Setting up path
PATH="/usr/games"
PATH="/usr/local/games:$PATH"
PATH="/sbin:$PATH"
PATH="/usr/sbin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="/usr/bin/core_perl:$PATH"
PATH="/usr/bin/vendor_perl:$PATH"
PATH="/usr/bin/site_perl:$PATH"
PATH="/bin:$PATH"
PATH="/usr/bin:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="/opt/maven/bin:$PATH"
PATH="/opt/wildfly/bin:$PATH"
PATH="$HOME/.composer/vendor/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.bin:$PATH"
PATH="$HOME/bin:$PATH"
PATH="$HOME/.nodenv/shims:$PATH"
PATH="$HOME/.nodenv/bin:$PATH"
PATH="$HOME/.rbenv/shims:$PATH"
PATH="$HOME/.rbenv/bin:$PATH"
export PATH

# Setting up editor
if [[ -n $SSH_TTY ]]; then
    export EDITOR="$SYSTEMCONF_VIM"
else
    export EDITOR="$SYSTEMCONF_VSCODE --wait"
fi

# Setting up variables
export ARCHFLAGS="-arch x86_64"
export CASE_SENSITIVE="false"
export CLICOLOR=1
export COLORTERM="truecolor"
export CSHEDIT="$SYSTEMCONF_VIM"
export COMPLETION_WAITING_DOTS="true"
export DIRSTACKSIZE=64
export DISABLE_AUTO_TITLE="true"
export DISABLE_LS_COLORS="false"
export DISABLE_MAGIC_FUNCTIONS="false"
export DISABLE_UNTRACKED_FILES_DIRTY="true"
export ENABLE_CORRECTION="true"
export HISTCONTROL="ignoredups"
export HISTFILE="$HOME/.zsh_history"
export HISTFILESIZE=99999
export HISTSIZE=99999
export HIST_STAMPS="yyyy-mm-dd"
export HYPHEN_INSENSITIVE="false"
export LANG="es_CL.UTF-8"
export LANGUAGE="es_CL.UTF-8"
export LC_ALL="es_CL.UTF-8"
export LC_ADDRESS="es_CL.UTF-8"
export LC_COLLATE="es_CL.UTF-8"
export LC_CTYPE="es_CL.UTF-8"
export LC_IDENTIFICATION="es_CL.UTF-8"
export LC_MEASUREMENT="es_CL.UTF-8"
export LC_MESSAGES="es_CL.UTF-8"
export LC_MONETARY="es_CL.UTF-8"
export LC_NAME="es_CL.UTF-8"
export LC_NUMERIC="es_CL.UTF-8"
export LC_PAPER="es_CL.UTF-8"
export LC_TELEPHONE="es_CL.UTF-8"
export LC_TIME="es_CL.UTF-8"
export MAILCHECK=60
export LS_OPTIONS='--color=always'
export MANPATH="/usr/local/man:/usr/share/man:$MANPATH"
export MANPATHISSET="yes"
export QUOTING_STYLE="literal"
export PAGER="$SYSTEMCONF_PAGER"
export SAVEHIST=99999
export SSH_KEY_PATH="$HOME/.ssh/chessandrock-ed25519"
export TEMPDIR="$HOME/.tmp/"
export VISUAL="$SYSTEMCONF_VIM"
export ZSH="$HOME/.oh-my-zsh"
export ZSH_COMPDUMP="$ZSH/cache/.zcompdump-$HOST"
export ZSH_THEME="pygmalion"
export ZSH_THEME_RANDOM_CANDIDATES=()

source "$HOME/.zsh-db-mariadb"
source "$HOME/.zsh-db-mongodb"
source "$HOME/.zsh-db-postgresql"
source "$HOME/.zsh-db-redis"
source "$HOME/.zsh-dev-node"
source "$HOME/.zsh-dev-ruby"
source "$HOME/.zsh-dev-php"
source "$HOME/.zsh-dev-java"
