#!/bin/zsh

PATH=/home/chessandrock/Anaconda/bin
PATH=$PATH:/home/chessandrock/Anaconda/condabin
PATH=$PATH:/home/chessandrock/.local/bin
PATH=$PATH:/home/chessandrock/bin
PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/bin
PATH=$PATH:/bin
PATH=$PATH:/usr/local/sbin
PATH=$PATH:/usr/sbin
PATH=$PATH:/sbin
export PATH

MANPATH=/usr/local/man:/usr/share/man
export MANPATH

export LANG="es_ES.UTF-8"
export LANGUAGE="es_ES.UTF-8"
export LC_ALL="es_ES.UTF-8"
export LC_ADDRESS="es_ES.UTF-8"
export LC_COLLATE="es_ES.UTF-8"
export LC_CTYPE="es_ES.UTF-8"
export LC_IDENTIFICATION="es_ES.UTF-8"
export LC_MEASUREMENT="es_ES.UTF-8"
export LC_MESSAGES="es_ES.UTF-8"
export LC_MONETARY="es_ES.UTF-8"
export LC_NAME="es_ES.UTF-8"
export LC_NUMERIC="es_ES.UTF-8"
export LC_PAPER="es_ES.UTF-8"
export LC_TELEPHONE="es_ES.UTF-8"
export LC_TIME="es_ES.UTF-8"

if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR="/usr/bin/vim"
else
    export EDITOR="/usr/bin/code --wait"
fi

export ARCHFLAGS="-arch x86_64"
export CASE_SENSITIVE="false"
export COLORTERM="truecolor"
export COMPLETION_WAITING_DOTS="true"
export DISABLE_AUTO_TITLE="true"
export DISABLE_LS_COLORS="false"
export DISABLE_MAGIC_FUNCTIONS="false"
export DISABLE_UNTRACKED_FILES_DIRTY="true"
export ENABLE_CORRECTION="true"
export HIST_STAMPS="yyyy-mm-dd"
export HISTCONTROL=ignoreboth
export HISTFILE=$HOME/.zsh_history
export HISTFILESIZE=99999
export HISTSIZE=99999
export HYPHEN_INSENSITIVE="true"
export MAIL=/var/mail/chessandrock
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="pygmalion"
export ZSH_THEME_RANDOM_CANDIDATES=( "pygmalion" )
